### ISSUE TITLE
Can I know what is this reset code for?

### ISSUE THREAD

**Issue by laireyx** [ImaginaryVillain/community_lights#111]
At the very beginning(line 8-24) of both Community_Lighting.js and Community_Lighting_MZ.js, there are a reset codes that overwrite some RMMZ global objects. However, upon investigation, I have concluded that this code may be unnecessary(in that the 'rpg_managers.js' file is not even importable through the require() function).

I kindly request clarification on the purpose and intended functionality of these specific lines of code. Could you please provide insight into their intended usage or confirm whether they can be safely removed without causing any adverse effects?

**Comment by ImaginaryVillain** [comment]
I have since abandoned RM, and am just pushing updates here due to community interest in the plugin. However all of the updates are done by the community now. You are welcome to experiment with the plugin as you see fit, or I recommend going to https://forums.rpgmakerweb.com/index.php?threads/community-lighting-mv-mz.124274/ and asking there. Perhaps whoever did it can give you better insight as to why it is as it is.
