### ISSUE TITLE
The "Daynight Initial Hour" field does not take effect in the latest version 5.0?

### ISSUE THREAD

**Issue by arrosev** [ImaginaryVillain/community_lights#112]
The plugin I use is "Community_Lighting_MZ.js", I have an old plugin with version 4.6 that works, and it seems that a lot of code has been removed in the plugin with version 5.0.

**Comment by arrosev** [comment]
I found that the cause of the white flashing window is this line of code "this.createTimeWindow();", which seems to be the time window.

**Comment by ImaginaryVillain** [comment]
Excellent, though I have since abandoned RM, and am just pushing updates here due to community interest in the plugin. However all of the updates are done by the community now. So you are welcome to experiment with the plugin as you see fit, or if you wish to have others write those changes,  I recommend going to https://forums.rpgmakerweb.com/index.php?threads/community-lighting-mv-mz.124274/ and asking there.
