### ISSUE TITLE
.gitignore is removing projects folders.

### ISSUE THREAD

**Issue by mnkyking** [ImaginaryVillain/community_lights#28]
I think code reviews and pull requests would benefit much more if the project files were available in the repo instead just the .zip. 
The .zip is great for easy downloads for new users. 

Does anyone oppose this change?

**Comment by AdriLez** [comment]
By default, RPG maker projects are ugly to look at when put on Github, simply because data files aren't formatted in an easily readable format (even for github). It means that any minor modification will appear as a full line change, it will not help at all for the reviews, quite the opposite.

It is however quite easy to add hook to git (https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks), to make those files look like a beautiful json object. This way it will be really helpful.

If we change to have the demos available (I'm in favor of it, it will make handling them easier), I think it is essential we add a 
such a hook.
