### ISSUE TITLE
Softer lights option

### ISSUE THREAD

**Issue by NerdyChara** [ImaginaryVillain/community_lights#34]
Hello. I am curious if it is possible to obtain softer light values with modifications to the light algorithm as opposed to the hard spotlight look this has. I am not entirely sure how the math currently works in here but I am curious. But I do know it uses radial gradients which is always a plus. If I knew if/how you use transparency that will be helpful as I think the soft effect could be accomplished with alphas. And I am also looking forward to brainstorming ideas.

**Comment by AdriLez** [comment]
The script for historical reasons use RGB values (red, green, blue, as hex number).
They have their merits but as you said it is difficult to decline a base color to get softer or darker variations of it.

An easy alternative is to use RGBA (red, green, blue, alpha), where alpha is basically the transparency.
They are represented also in hex with two additional hex number (ff = no transparency, 00 = 100% transparent).
#FF0000 (pure red) is the same as #FF0000FF. #FF000080 is a pure red color but with 50% transparency.
RPG maker MV/MZ uses it in rare circonstances, notably the dark message box.

RGBA are currently not supported by the script at all since finding a softer alternative color with a color picker was generally a good enough solution.

**Comment by NerdyChara** [comment]
`/**
   * 
   * @param {String} hex 
   * @returns {{r:number,g:number,b:number,a:number}}
   */
  function hexToRgb(hex) {
    var regex = new RegExp(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})?$/i);
    let result = regex.exec(hex);
    result = result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16),
      a: result[4] == null ? 255 : parseInt(result[4], 16)
    } : null;
    return result;
  }
`

I was thinking about modifying the hex to rgb function to be like this. What do you think?

**Comment by mnkyking** [comment]
yeah that looks good to me I am assuming \d is for digits but don't know what `/i` is for. The first 6 values should be required in my opinion to avoid issues while the 4th value is optional

**Comment by AdriLez** [comment]
> yeah that looks good to me I am assuming \d is for digits but don't know what `/i` is for. The first 6 values should be required in my opinion to avoid issues while the 4th value is optional

The final /i stands for case insensitive searchs. 
https://www.w3schools.com/jsref/jsref_regexp_i.asp

**Comment by AdriLez** [comment]
About your method it sounds correct to me.

**Comment by AdriLez** [comment]
Actually, I just realized the plugin never properly supported 3 hex digits colors.
